/**
 * @license
 * Copyright Google LLC All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.dev/license
 */

/* Manual type definitions for Sidecar mode — Auto-generated from ng-analyze/index.d.ts */

export type FileId = number;

/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Standalone iterator produced by `Analyzer::analyze()` for streaming results. */
export declare class AnalysisIterator {
  next(): Promise<CompilationChunk | null>;
}

export declare class Analyzer {
  constructor(options: AnalyzerOptions);
  getTsFileForTemplate(templatePath: string): Array<TemplateUsage> | null;
  updateFileContent(updates: Array<FileUpdate>): Array<string>;
  invalidateFiles(updates: Array<FileInvalidation>): Array<string>;
  analyze(): AnalysisIterator;
  analyzeOptimized(): AnalysisIterator;
  analyzeDelta(): AnalysisIterator;
  analyzeOptimizedDelta(): AnalysisIterator;
  getMetadataForFile(filePath: string): AnalysisResult | null;
  getFileContent(filePath: string): string;
}

/** Test analyzer that uses virtual filesystem for in-memory testing */
export declare class TestAnalyzer {
  constructor(options: TestAnalyzerOptions);
  getMetadataForFile(filePath: string): AnalysisResult | null;
  getFileContent(filePath: string): string;
  getTsFileForTemplate(templatePath: string): Array<TemplateUsage> | null;
  updateFileContent(updates: Array<FileUpdate>): Array<string>;
  invalidateFiles(updates: Array<FileInvalidation>): Array<string>;
  analyze(): AnalysisIterator;
  analyzeOptimized(): AnalysisIterator;
  analyzeDelta(): AnalysisIterator;
  analyzeOptimizedDelta(): AnalysisIterator;
}

export interface AnalysisResult {
  fileId: FileId;
  filePath: string;
  importsEnd: number;
  classes: Array<ClassMetadata>;
  /**
   * The file's static `import` declarations, in source order, so consumers never have to
   * re-parse the source to find or edit an import.
   */
  imports: Array<ImportDeclarationMetadata>;
  typeOnlyExports: Array<string>;
  diagnostics: Array<NgDiagnostic>;
}

export interface AnalyzerOptions {
  tsconfigPath: string;
  optimize?: boolean;
  virtualFiles?: Record<string, string>;
  nodeModulesPathOverride?: string;
  /**
   * Optional list of absolute file paths for source files (JS/TS) that the analyzer is allowed to read from the physical disk.
   *
   * If provided, physical file system access for JS/TS files will be restricted to only these paths.
   * This is used to enforce build boundaries (e.g., in Bazel) by blocking restricted source files,
   * forcing the resolver to fall back to allowed `.d.ts` files.
   *
   * Symlinks in this list are handled automatically; both the symlink path and its resolved
   * physical path will be allowed.
   */
  allowedSources?: Array<string>;
  /** Workspace name used by `PrefixImportStrategy` for module specifiers (e.g., "google3"). */
  workspaceName?: string;
  /** Root directories used by `PrefixImportStrategy` to strip prefixes. */
  rootDirs?: Array<string>;
}

export interface AngularFieldMetadata {
  kind: string;
  input?: InputMetadata;
  output?: OutputMetadata;
  query?: QueryMetadata;
  coercion?: string;
}

export interface ClassMetadata {
  symbolId: number;
  span: SpanMetadata;
  decoratedSpan: SpanMetadata;
  nameSpan?: SpanMetadata;
  className?: string;
  ref?: ReferenceMetadata;
  constructorParams?: Array<ConstructorParamMetadata>;
  memberDecorators?: Array<DecoratedMemberMetadata>;
  injectable?: InjectableMetadata;
  service?: ServiceMetadata;
  component?: ComponentMetadata;
  directive?: DirectiveMetadata;
  pipe?: PipeMetadata;
  ngModule?: NgModuleMetadata;
  fields: Array<AngularFieldMetadata>;
  flattenedFields?: Array<AngularFieldMetadata>;
  /**
   * Member API surface pre-derived from `fields`: `model()` members are expanded into a
   * signal input plus a `<name>Change` output, and inputs matched by an
   * `ngAcceptInputType_` coercion member are marked coerced. Query lists are sorted
   * signal-first, then `first`, then the rest (stable). `fields` stays on the wire for
   * consumers that need the raw per-member view (TCB adapter, indexer).
   */
  inputs: Array<InputMetadata>;
  outputs: Array<OutputMetadata>;
  queries: Array<QueryMetadata>;
  viewQueries: Array<QueryMetadata>;
  /**
   * Every span the preprocessor must delete for this class: the class's Angular decorators
   * plus each member-level `@Input`/`@Output`/query/`@HostBinding`/`@HostListener`
   * decorator.
   */
  removalSpans: Array<SpanMetadata>;
  /**
   * The ready-to-splice `declare static ngAcceptInputType_...` member block for
   * decorator-based inputs with a `transform`, empty when there are none.
   */
  coercionMembers: string;
  hostBindings: Array<HostBindingMetadata>;
  hostListeners: Array<HostListenerMetadata>;
  typeParameters?: Array<TypeParameterMetadata>;
  hasNgTemplateContextGuard: boolean;
  ngTemplateGuards: Array<TemplateGuardMetadata>;
  hasNgFieldDirective: boolean;
  superClass?: DeclarationTuple;
  usesInheritance: boolean;
  usesOnChanges: boolean;
  isExported: boolean;
  hasNonExportedBounds: boolean;
}

export interface CompilationChunk {
  files: Array<AnalysisResult>;
  staticEdges?: Record<string, Array<FileId>>;
}

export interface ComponentMetadata {
  decoratorName?: string;
  selector?: string;
  imports?: Array<ReferenceMetadata>;
  template?: string;
  templateOffset?: number;
  /**
   * The inline `template` property's value expression span — the node ngtsc anchors
   * template-attributed diagnostics on when the template is declared inline.
   */
  templateSpan?: SpanMetadata;
  /**
   * True when an inline `template` was present but not statically resolvable
   * (dynamic template literal). Signals the processor to fall back to JIT / error
   * rather than emit an empty template.
   */
  templateDynamic: boolean;
  templateUrl?: UrlMetadata;
  styles?: Array<string>;
  stylesFromUrls?: Array<string>;
  styleUrls?: Array<UrlMetadata>;
  standalone: boolean;
  signals: boolean;
  exportAs?: Array<string>;
  schemas?: Array<string>;
  rawImportsSpan?: SpanMetadata;
  /**
   * Preserved copy of `@Component.imports` expression span, unaffected by same-file scope
   * resolution. Required by local compilation mode for runtime dependency resolution.
   */
  importsFactorySpan?: SpanMetadata;
  resolvedDeclarations?: Array<DeclarationMetadata>;
  /**
   * Whether the declaring `@NgModule`'s scope is exactly what ngtsc would have computed.
   * `None` for a standalone component, which has no declaring NgModule, and for a
   * non-standalone component whose declaring NgModule could not be found at all.
   *
   * `Some(false)` means `resolved_declarations` is not authoritative, and it arises two ways:
   *
   * - An entry of `imports`/`declarations` was not a static `Reference`. ngtsc throws NG1010
   *   and drops the NgModule, leaving the component with a *null* scope, so
   *   `resolved_declarations` is emptied to match and the template is checked against
   *   nothing — see `optimize_component`.
   * - A `Reference` resolved statically but this analyzer could not follow it to a class.
   *   ngtsc has no such failure; `resolved_declarations` then holds the *subset* that did
   *   resolve, as a best-effort divergence so the type-check block is not starved.
   *
   * Either way the static `dependencies` list must be withheld from `ɵcmp` and the component
   * left out of remote scoping, since both would pin it to a scope that is not its real one.
   */
  scopeIsComplete?: boolean;
  /**
   * Module specifiers to emit as bare side-effect imports (`import '<specifier>';`) in
   * local compilation mode, mirroring ngtsc's `LocalCompilationExtraImportsTracker`.
   *
   * Only populated for a non-standalone `@Component` whose declaring `@NgModule` lives in a
   * different file: those are the files ngtsc marks via `markFileForExtraImportGeneration`.
   * The specifiers are already projected into this component file's frame by Rust; the
   * emitter must use them verbatim.
   */
  localCompilationExtraImports?: Array<string>;
  /** Syntax of the `host` object literal, for the type-check block. */
  hostProperties: Array<HostPropertyMetadata>;
  /**
   * The `host` property's value expression span — the node ngtsc anchors host binding
   * parse/verify diagnostics on.
   */
  hostSpan?: SpanMetadata;
  /**
   * The `host` object reduced by the partial evaluator, in source order. `None` when the
   * decorator has no `host` field or it did not evaluate to an object.
   */
  hostMetadata?: Array<HostMetadataEntry>;
  /** Raw hostDirectives expression from the decorator */
  hostDirectives?: Array<HostDirectiveMetadata>;
  providersSpan?: SpanMetadata;
  viewProvidersSpan?: SpanMetadata;
  /**
   * `encapsulation` resolved to its numeric `ViewEncapsulation` member value, mirroring
   * ngtsc's `resolveEnumValue`, with its textual local-compilation resolver
   * (`resolveEncapsulationEnumValueLocally`) as the fallback. `None` when absent or
   * unresolved — consumers default to `Emulated`.
   * https://github.com/angular/angular/blob/83622ee/packages/compiler-cli/src/ngtsc/annotations/component/src/handler.ts#L532-L542
   */
  encapsulation?: number;
  /** `changeDetection` expression as written in the decorator, matching ngtsc's local compilation behavior. `None` when absent. */
  changeDetection?: string;
  preserveWhitespaces?: boolean;
  animationsSpan?: SpanMetadata;
  animationTriggerNames?: LegacyAnimationTriggerNames;
  argsSpan?: SpanMetadata;
  preservedDecoratorProperties?: Array<SpanMetadata>;
  declaringNgModule?: DeclaringNgModule;
  foreignImports?: Array<ForeignImportMetadata>;
  isJit: boolean;
  deferredImports?: Array<ReferenceMetadata>;
  deferredImportsByBlock?: Record<string, Array<ReferenceMetadata>>;
  deferredImportsSpan?: SpanMetadata;
  resolvedDeferredDeclarations?: Array<DeclarationMetadata>;
  resolvedDeferredDeclarationsByBlock?: Record<string, Array<DeclarationMetadata>>;
}

export interface ConstructorParamMetadata {
  typeName?: string;
  /**
   * Module specifier the type was imported from, when the type resolves to a (non-aliased)
   * named import (e.g. `@angular/core` for `ElementRef`). `None` for locally declared types.
   * Used so DI tokens that reference an imported symbol are emitted through the matching
   * namespace import (e.g. `i0.ElementRef`), mirroring ngtsc's import manager.
   */
  typeModule?: string;
  isTypeOnly: boolean;
  /**
   * Whether `type_name` was resolved to a declaration that has a runtime value, either in this
   * file or by chasing the import across files. References we could not resolve at all —
   * ambient globals, members of an ambient namespace, specifiers outside the compilation — are
   * emitted optimistically, so the `ɵsetClassMetadata` entry has to be guarded with
   * `@ts-ignore`. This is the inverse of ngtsc's `TypeValueReference#valueUnverified`.
   */
  isValueVerified: boolean;
  decorators: Array<DecoratorMetadata>;
}

export interface DeclarationMetadata {
  name: string;
  ref: ReferenceMetadata;
  /**
   * The same declaration as seen from the file of the NgModule declaring this component's
   * owner — what remote scoping must emit, since `ɵɵsetComponentScope` is written there.
   */
  refInDeclaringModule?: ReferenceMetadata;
  nameSpan: SpanMetadata;
  declarationType: string;
  selector?: string;
  pipeName?: string;
  isStandalone?: boolean;
  exportAs?: Array<string>;
  fileId: FileId;
  filePath?: string;
  hostDirectives?: Array<HostDirectiveMetadata>;
  fields?: Array<AngularFieldMetadata>;
  flattenedFields?: Array<AngularFieldMetadata>;
  ngContentSelectors?: Array<string>;
  typeParameters?: Array<TypeParameterMetadata>;
  hasNgTemplateContextGuard: boolean;
  ngTemplateGuards: Array<TemplateGuardMetadata>;
  animationTriggerNames?: LegacyAnimationTriggerNames;
  hasNgFieldDirective: boolean;
  isForwardRef: boolean;
  isStructural: boolean;
  cycleProne?: boolean;
  isExported: boolean;
  hasNonExportedBounds: boolean;
  isExplicitlyDeferred: boolean;
  deferredBlocks?: Array<string>;
}

export interface DeclarationTuple {
  localName: string;
  importSource?: string;
}

export interface DeclaringNgModule {
  filePath: string;
  symbolId: number;
}

/**
 * A non-static, non-private class member that carries at least one decorator. Mirrors the
 * per-member entries ngtsc builds for the property-decorator map of `ɵsetClassMetadata`.
 * https://github.com/angular/angular/blob/83622ee/packages/compiler-cli/src/ngtsc/annotations/common/src/metadata.ts#L91-L131
 */
export interface DecoratedMemberMetadata {
  propertyName: string;
  /** Whether the member name must be quoted (the name node is a string literal). */
  isStringLiteral: boolean;
  decorators: Array<DecoratorMetadata>;
}

export interface DecoratorArg {
  value: string;
  isLiteral: boolean;
}

/** A single decorator captured on a class member or constructor parameter for `ɵsetClassMetadata`. */
export interface DecoratorMetadata {
  name: string;
  canonicalName?: string;
  args?: Array<DecoratorArg>;
  decoratorSpan?: SpanMetadata;
  /**
   * Span of the decorator's argument list (first arg start..last arg end), used to emit the
   * `args: [...]` of `ɵsetClassMetadata` verbatim from source. `None` when there are no args.
   */
  argsSpan?: SpanMetadata;
  /**
   * Pre-rendered argument string with type arguments stripped (e.g. for `ChildComponent<T>` -> `ChildComponent`),
   * emitted when generic type arguments are stripped for static block compatibility in `ɵsetClassMetadata`.
   */
  argsString?: string;
  /**
   * Whether the decorator is imported from `@angular/core`. Only Angular decorators are
   * captured in the `ɵsetClassMetadata` constructor-parameter metadata.
   * https://github.com/angular/angular/blob/83622ee/packages/compiler-cli/src/ngtsc/annotations/common/src/metadata.ts#L172-L179
   */
  isAngular: boolean;
}

export interface DependencyMetadata {
  tokenSpan?: SpanMetadata;
  host: boolean;
  optional: boolean;
  self: boolean;
  skipSelf: boolean;
}

export interface DirectiveMetadata {
  decoratorName?: string;
  selector?: string;
  standalone: boolean;
  signals: boolean;
  isStructural: boolean;
  exportAs?: Array<string>;
  /** Syntax of the `host` object literal, for the type-check block. */
  hostProperties: Array<HostPropertyMetadata>;
  /**
   * The `host` property's value expression span — the node ngtsc anchors host binding
   * parse/verify diagnostics on.
   */
  hostSpan?: SpanMetadata;
  /**
   * The `host` object reduced by the partial evaluator, in source order. `None` when the
   * decorator has no `host` field or it did not evaluate to an object.
   */
  hostMetadata?: Array<HostMetadataEntry>;
  /** Raw hostDirectives expression from the decorator */
  hostDirectives?: Array<HostDirectiveMetadata>;
  providersSpan?: SpanMetadata;
  argsSpan?: SpanMetadata;
  declaringNgModule?: DeclaringNgModule;
  isJit: boolean;
}

export enum ExpressionValueKindMetadata {
  String = 'string',
  Identifier = 'identifier',
  Unspecified = 'unspecified',
}

export interface ExpressionValueMetadata {
  kind: ExpressionValueKindMetadata;
  text?: string;
  sourceSpan: SpanMetadata;
}

export interface FileInvalidation {
  filePath: string;
  updateType: FileUpdateType;
}

export interface FileUpdate {
  filePath: string;
  content: string;
}

export enum FileUpdateType {
  Created = 0,
  Deleted = 1,
  Changed = 2,
}

export interface ForeignImportMetadata {
  name: string;
  span: SpanMetadata;
}

export interface HostBindingMetadata {
  memberName: ExpressionValueMetadata;
  arguments: Array<ExpressionValueMetadata>;
  decoratorSpan: SpanMetadata;
  memberSpan: SpanMetadata;
}

export interface HostDirectiveBinding {
  publicName: string;
  bindingName: string;
}

export interface HostDirectiveMetadata {
  directive: string;
  inputs?: Array<HostDirectiveBinding>;
  outputs?: Array<HostDirectiveBinding>;
  isForwardRef: boolean;
}

export interface HostListenerMetadata {
  methodName: ExpressionValueMetadata;
  eventName: ExpressionValueMetadata;
  args: Array<ExpressionValueMetadata>;
  runtimeArgs?: Array<string>;
  decoratorSpan: SpanMetadata;
  memberSpan: SpanMetadata;
}

/**
 * One entry of the `host` object as the partial evaluator reduced it. Mirror of ngtsc's
 * `hostMetadata: Record<string, string | Expression>`, whose values are either a folded
 * string or a `WrappedNodeExpr` over an unevaluable node:
 * https://github.com/angular/angular/blob/1c9c453/packages/compiler-cli/src/ngtsc/annotations/directive/src/shared.ts#L2021-L2047
 */
export interface HostMetadataEntry {
  key: string;
  /**
   * The string the evaluator folded this entry to. Exactly one of `value` and `expression`
   * is set.
   */
  value?: string;
  /** Source text of a value that is not statically evaluable, for verbatim re-emission. */
  expression?: string;
}

export interface HostPropertyMetadata {
  key: ExpressionValueMetadata;
  value: ExpressionValueMetadata;
}

/** How to write an import for a symbol, if the consumer decides it needs one. */
export interface ImportableRef {
  /** Module specifier to import from. */
  specifier: string;
  /**
   * The name `specifier` exports the symbol under — not necessarily its declared name, since
   * a barrel may rename on the way through, nor its name in the consuming file.
   */
  symbol: string;
}

/** One binding introduced by a static `import` declaration. */
export interface ImportBindingMetadata {
  /** The identifier this declaration binds in the importing file. */
  local: string;
  /**
   * The name the module exports this binding under: the named export, the reserved key
   * `"default"` for a default import, or absent for a namespace import (`import * as ns`),
   * which binds the module object itself rather than any one export.
   */
  imported?: string;
  /**
   * Whether a reference to `local` survives the edits this compiler makes to the file, so
   * the binding must keep its import. References inside a component's `imports: [...]` array
   * do not count — the decorator is stripped from the output.
   */
  eagerlyReferenced: boolean;
  /**
   * Whether any such surviving reference is in value position, i.e. would still be there if
   * this compiler emitted JavaScript. ngtsc decides deferrability on this narrower set, so
   * it is what reproducing an ngtsc diagnostic needs; `eagerly_referenced` is what deciding
   * whether the declaration may be deleted from *this* compiler's TypeScript output needs.
   */
  valueReferenced: boolean;
  /**
   * `import type { X }` / `import { type X }`: the binding exists only in type position.
   * ngtsc ignores these entirely when deciding whether a declaration can be deferred.
   */
  isType: boolean;
}

/**
 * A static `import` declaration: enough to decide whether it may be dropped in favour of the
 * dynamic `import()`s a `@defer` block emits, and the exact range to delete when it may.
 *
 * Removal is all-or-nothing per declaration, matching ngtsc's `DeferredSymbolTracker`.
 */
export interface ImportDeclarationMetadata {
  /** The declaration's own span, for anchoring a diagnostic on the statement. */
  span: SpanMetadata;
  /**
   * `span` extended over a trailing line terminator, so deleting it leaves no blank line
   * behind. Only removal wants the extension; a diagnostic underlining it would drag the
   * squiggle onto the next line.
   */
  removalSpan: SpanMetadata;
  /** The module specifier, verbatim (unresolved). */
  specifier: string;
  /**
   * Every binding the declaration introduces, including type-only ones. A bare
   * `import './side-effect'` introduces none, and can never be removed.
   */
  bindings: Array<ImportBindingMetadata>;
}

export interface ImportViaMetadata {
  moduleSpecifier: string;
  symbol?: string;
}

export interface InjectableMetadata {
  decoratorName?: string;
  providedIn?: ProviderField;
  useClass?: ProviderField;
  useExisting?: ProviderField;
  useFactory?: ProviderField;
  useValue?: ProviderField;
  argsSpan?: SpanMetadata;
  deps?: Array<DependencyMetadata>;
}

export interface InputMetadata {
  name: string;
  alias?: string;
  required: boolean;
  isSignal: boolean;
  decoratorSpan?: SpanMetadata;
  propertySpan?: SpanMetadata;
  transform?: TransformMetadata;
  isRestricted: boolean;
  isLiteral: boolean;
  isCoerced: boolean;
}

export interface LegacyAnimationTriggerNames {
  staticTriggerNames: Array<string>;
  includesDynamicAnimations: boolean;
}

export interface NgDiagnostic {
  category: number;
  code: number;
  messageText: string;
  filePath?: string;
  span?: SpanMetadata;
}

export interface NgModuleMetadata {
  decoratorName?: string;
  /**
   * True when any declaration or import of this NgModule came from a `forwardRef`-like
   * foreign resolver, so the runtime value may not be available when `ɵɵsetComponentScope`
   * runs and remote-scope arrays must be wrapped in a closure.
   * https://github.com/angular/angular/blob/c1829f6/packages/compiler-cli/src/ngtsc/annotations/ng_module/src/handler.ts#L705-L706
   */
  remoteScopesMayRequireCycleProtection: boolean;
  declarations?: Array<ReferenceMetadata>;
  imports?: Array<ReferenceMetadata>;
  injectorImports?: Array<ReferenceMetadata>;
  exports?: Array<ReferenceMetadata>;
  bootstrap?: Array<ReferenceMetadata>;
  /**
   * `imports` elements to re-emit verbatim into `ɵinj.imports` because they contain a
   * `ModuleWithProviders` call. `index` is the position in the final list, interleaved
   * with the resolved injector imports.
   */
  injectorImportRawSpans?: Array<RawInjectorImportMetadata>;
  providersSpan?: SpanMetadata;
  idSpan?: SpanMetadata;
  schemas?: Array<string>;
  argsSpan?: SpanMetadata;
  /**
   * Raw source spans of the `declarations`/`imports`/`exports`/`bootstrap` value
   * expressions, emitted verbatim in LOCAL compilation mode's `ɵɵsetNgModuleScope`.
   */
  declarationsSpan?: SpanMetadata;
  importsSpan?: SpanMetadata;
  exportsSpan?: SpanMetadata;
  bootstrapSpan?: SpanMetadata;
  /**
   * Raw source spans of the top-level `imports`/`exports` array elements, emitted
   * verbatim (concatenated) in LOCAL compilation mode's `ɵinj.imports`.
   */
  localImportsElementSpans?: Array<SpanMetadata>;
  localExportsElementSpans?: Array<SpanMetadata>;
}

export interface OutputMetadata {
  name: string;
  alias?: string;
  decoratorSpan?: SpanMetadata;
  propertySpan?: SpanMetadata;
  isSignal: boolean;
}

export interface PipeMetadata {
  decoratorName?: string;
  name: string;
  pure?: boolean;
  standalone?: boolean;
  argsSpan?: SpanMetadata;
  declaringNgModule?: DeclaringNgModule;
}

export interface ProviderField {
  span: SpanMetadata;
  isForwardRef: boolean;
}

export interface QueryMetadata {
  propertyName: string;
  first: boolean;
  isForwardRef: boolean;
  predicateSpan: SpanMetadata;
  isPredicateString: boolean;
  descendants: boolean;
  emitDistinctChangesOnly: boolean;
  readSpan?: SpanMetadata;
  isStatic: boolean;
  isSignal: boolean;
  decoratorSpan?: SpanMetadata;
  isView: boolean;
  propertySpan?: SpanMetadata;
}

export interface RawInjectorImportMetadata {
  index: number;
  span: SpanMetadata;
}

/**
 * How a consuming file can refer to a symbol. The two fields are independent facts, not a
 * two-state choice: a cross-file symbol the consumer already imports has both, and callers
 * pick per use — an eager reference wants the local binding, while a `@defer` block writes
 * How a consuming file can refer to a symbol. Encodes how to reference the target both in-situ
 * (within the consumer file) and for type-checking (.ngtypecheck.ts).
 */
export interface ReferenceMetadata {
  /** How to import the target into the consumer file (in-situ), if not bound locally. */
  consumerImport?: ImportableRef;
  /** How to import the target into an external type-checking file (.ngtypecheck.ts). */
  typecheckImport?: ImportableRef;
  /** Identifier in the consumer file's lexical scope (for same-file declarations or local aliases). */
  localAlias?: string;
}

export interface ServiceMetadata {
  decoratorName?: string;
  autoProvided?: boolean;
  factory?: ProviderField;
  argsSpan?: SpanMetadata;
}

export interface SpanMetadata {
  start: number;
  end: number;
}

export interface TemplateGuardMetadata {
  inputName: string;
  type: string;
}

export interface TemplateUsage {
  tsFilePath: string;
  symbolId: number;
}

/** Options for creating a test analyzer */
export interface TestAnalyzerOptions {
  /** Virtual files to use for analysis */
  virtualFiles: Record<string, string>;
  /** Whether to use optimized two-pass mode */
  optimize?: boolean;
  /** Path to tsconfig.json (must be a virtual file path) */
  tsconfigPath: string;
  /** Path to real node_modules for resolving @angular packages */
  nodeModulesPathOverride?: string;
  /** Workspace name used by `PrefixImportStrategy` (e.g. "google3") */
  workspaceName?: string;
  /** Root directories for `PrefixImportStrategy` */
  rootDirs?: Array<string>;
}

export interface TransformMetadata {
  kind: string;
  span: SpanMetadata;
  typeSpan?: SpanMetadata;
}

export interface TypeParameterMetadata {
  name: string;
  representation: string;
  representationWithDefault: string;
  hasDefault: boolean;
  typeRefs?: Array<TypeRefMetadata>;
}

export interface TypeRefMetadata {
  name: string;
  moduleSpecifier: string;
  symbol: string;
  span?: SpanMetadata;
}

/**
 * `UrlMetadata` represents a URL resource (like a template or style sheet URL) referenced in a component decorator.
 * It tracks the raw URL string, the resolved absolute file path, and the exact text span of the string literal
 * in the source file. This is crucial for the Kythe indexer to establish cross-references (links) from the
 * TypeScript source files to the external HTML/CSS files.
 */
export interface UrlMetadata {
  url: string;
  resolvedPath: string;
  stringLiteralSpan?: SpanMetadata;
}
